"""
Sequence manager — translates transformer test definitions into ordered,
relay-mapped test steps ready for execution by the test engine.
"""
from typing import List, Dict, Optional, Tuple
from dataclasses import dataclass, field

from core.config_loader import TransformerConfig, TestStep, WindingConfig


@dataclass
class ExecutableStep:
    """A single actionable test step with all relay assignments resolved."""
    index: int
    description: str
    from_winding_id: str
    to_winding_id: str
    expected_voltage: float
    tolerance_percent: float
    measurement_channel: int
    stabilization_delay_ms: int
    relays_to_close: List[int] = field(default_factory=list)   # relay IDs to energize
    relays_to_open: List[int] = field(default_factory=list)    # relay IDs to de-energize
    relay_map: Dict[int, bool] = field(default_factory=dict)   # full relay state for this step
    from_tap_index: Optional[int] = None
    to_tap_index: Optional[int] = None


class SequenceManager:
    """
    Builds an ordered list of ExecutableSteps from a TransformerConfig.
    Handles relay assignment based on winding relay_id fields and
    explicit relay_map overrides in test definitions.
    """

    def __init__(self):
        self._steps: List[ExecutableStep] = []
        self._current_index: int = -1
        self._transformer_config: Optional[TransformerConfig] = None

    # ------------------------------------------------------------------ #
    #  Public API                                                         #
    # ------------------------------------------------------------------ #

    def load(self, config: TransformerConfig) -> List[ExecutableStep]:
        """
        Build executable steps from config.

        When config.auto_matrix.enabled is True the full validation sweep is
        auto-generated by MeasurementMatrixEngine (requirements 37-52).
        Otherwise the explicit 'tests' array is used.

        Returns the full list so callers can inspect before running.
        """
        self._transformer_config = config
        self._steps = []
        self._current_index = -1

        if config.auto_matrix.enabled:
            from core.measurement_matrix_engine import MeasurementMatrixEngine
            self._steps = MeasurementMatrixEngine().build_matrix(config)
        else:
            winding_map = self._build_winding_map(config)
            for idx, test in enumerate(config.tests):
                self._steps.append(self._resolve_step(idx, test, winding_map))

        return list(self._steps)

    def reset(self) -> None:
        self._current_index = -1

    @property
    def steps(self) -> List[ExecutableStep]:
        return list(self._steps)

    @property
    def total_steps(self) -> int:
        return len(self._steps)

    @property
    def current_index(self) -> int:
        return self._current_index

    def has_next(self) -> bool:
        return self._current_index < len(self._steps) - 1

    def advance(self) -> Optional[ExecutableStep]:
        """Move to next step and return it, or None if exhausted."""
        if not self.has_next():
            return None
        self._current_index += 1
        return self._steps[self._current_index]

    def current_step(self) -> Optional[ExecutableStep]:
        if self._current_index < 0 or self._current_index >= len(self._steps):
            return None
        return self._steps[self._current_index]

    def get_step(self, index: int) -> Optional[ExecutableStep]:
        if 0 <= index < len(self._steps):
            return self._steps[index]
        return None

    def seek(self, index: int) -> bool:
        """Jump to a specific step index (manual mode)."""
        if 0 <= index < len(self._steps):
            self._current_index = index - 1   # advance() will increment
            return True
        return False

    # ------------------------------------------------------------------ #
    #  Internal helpers                                                   #
    # ------------------------------------------------------------------ #

    @staticmethod
    def _build_winding_map(config: TransformerConfig) -> Dict[str, WindingConfig]:
        result = {}
        for w in config.primary:
            result[w.id] = w
        for w in config.secondary:
            result[w.id] = w
        return result

    @staticmethod
    def _resolve_step(idx: int, test: TestStep,
                      winding_map: Dict[str, WindingConfig]) -> ExecutableStep:
        """
        Resolve relay assignments for a test step.
        Priority: explicit relay_map in test definition > winding relay_id fields.
        """
        from_w = winding_map.get(test.from_winding)
        to_w = winding_map.get(test.to_winding)

        # Start from relay_map in the test definition (if provided)
        relay_map: Dict[int, bool] = dict(test.relay_map) if test.relay_map else {}

        # Auto-assign winding relays if not overridden
        if from_w and from_w.relay_id is not None and from_w.relay_id not in relay_map:
            relay_map[from_w.relay_id] = True
        if to_w and to_w.relay_id is not None and to_w.relay_id not in relay_map:
            relay_map[to_w.relay_id] = True

        relays_to_close = [rid for rid, state in relay_map.items() if state]
        relays_to_open  = [rid for rid, state in relay_map.items() if not state]

        desc = test.description or f"Test {test.from_winding} → {test.to_winding}"

        return ExecutableStep(
            index=idx,
            description=desc,
            from_winding_id=test.from_winding,
            to_winding_id=test.to_winding,
            expected_voltage=test.expected_voltage,
            tolerance_percent=test.tolerance_percent,
            measurement_channel=test.measurement_channel,
            stabilization_delay_ms=test.stabilization_delay_ms,
            relays_to_close=relays_to_close,
            relays_to_open=relays_to_open,
            relay_map=relay_map,
            from_tap_index=test.from_tap_index,
            to_tap_index=test.to_tap_index,
        )
